name: Cypress Tests Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Cache node_modules and Cypress binary to speed up builds
      - name: Cache Node.js modules and Cypress binary
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 4: Install project dependencies, including Cypress
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Step 5: Install Cypress binary
      - name: Install Cypress
        run: npx cypress install

      # Step 6: Verify Cypress installation
      - name: Verify Cypress
        run: npx cypress verify

      # Step 7: Run basic Cypress tests
      - name: Run Basic Cypress Tests
        run: npx cypress run --spec "cypress/e2e/basicTests.spec.js"

      # Step 8: Upload test failure artifacts (screenshots, videos) if needed
      - name: Upload Cypress Screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress Videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
